name: "More-Behaviors"

web: "[clientcide.com](http://clientcide.com)"

description: "Behavior filters for MooTools More"

license: "MIT License"

copyright: "&copy; [Aaron Newton](http://clientcide.com)"

authors: "[Aaron Newton](http://clientcide.com)"

version: "1.0.1"

sources:
  - "Source/Fx/Behavior.FxAccordion.js"
  - "Source/Forms/Behavior.FormRequest.js"
  - "Source/Forms/Behavior.FormValidator.js"
  - "Source/Forms/Behavior.OverText.js"
  - "Source/Interface/Behavior.HtmlTable.js"
  - "Source/Drag/Behavior.Resizable.js"
  - "Source/Drag/Behavior.Sortable.js"
  - "Source/Delegators/Delegator.AddRemoveClass.js"
  - "Source/Delegators/Delegator.Ajax.js"
  - "Source/Delegators/Delegator.CheckAllOrNone.js"
  - "Source/Delegators/Delegator.FxReveal.js"
  - "Source/Delegators/Delegator.SetProperty.js"
  - "Source/Delegators/Delegator.SubmitLink.js"
